#!/bin/bash
# Script de normalización para Servidor Alfa (/imagenes/EVIDENCIAS DE OBRAS 2026/)
cd "/imagenes/EVIDENCIAS DE OBRAS 2026" 2>/dev/null || cd "/var/www/html/imagenes/EVIDENCIAS DE OBRAS 2026" 2>/dev/null || exit 1

if [ -d "COLECTOR/MT-DGOP-PROAGUA-FAISMUN-LPN-097-2026" ]; then mv "COLECTOR/MT-DGOP-PROAGUA-FAISMUN-LPN-097-2026" "COLECTOR/FENA-097"; fi
if [ -f "COLECTOR/FENA-097/INICIAL.jpeg" ]; then mv "COLECTOR/FENA-097/INICIAL.jpeg" "COLECTOR/FENA-097/_inicio.jpeg"; fi
if [ -f "COLECTOR/FENA-097/PROCESO.jpeg" ]; then mv "COLECTOR/FENA-097/PROCESO.jpeg" "COLECTOR/FENA-097/_proceso.jpeg"; fi
if [ -d "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-061-2026" ]; then mv "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-061-2026" "CONCRETOS ECOLOGICOS/TERRA-061"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-061/INICIO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-061/INICIO.jpeg" "CONCRETOS ECOLOGICOS/TERRA-061/_inicio.jpeg"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-061/PROCESO.jpg" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-061/PROCESO.jpg" "CONCRETOS ECOLOGICOS/TERRA-061/_proceso.jpg"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-061/TERMINADO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-061/TERMINADO.jpeg" "CONCRETOS ECOLOGICOS/TERRA-061/_terminado.jpeg"; fi
if [ -d "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-062-2026" ]; then mv "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-062-2026" "CONCRETOS ECOLOGICOS/IAP-062"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-062/INICIO.JPG" ]; then mv "CONCRETOS ECOLOGICOS/IAP-062/INICIO.JPG" "CONCRETOS ECOLOGICOS/IAP-062/_inicio.jpg"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-062/PROCESO.JPG" ]; then mv "CONCRETOS ECOLOGICOS/IAP-062/PROCESO.JPG" "CONCRETOS ECOLOGICOS/IAP-062/_proceso.jpg"; fi
if [ -d "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-063-2026" ]; then mv "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-063-2026" "CONCRETOS ECOLOGICOS/IAP-063"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-063/INICIO.JPG" ]; then mv "CONCRETOS ECOLOGICOS/IAP-063/INICIO.JPG" "CONCRETOS ECOLOGICOS/IAP-063/_inicio.jpg"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-063/PROCESO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/IAP-063/PROCESO.jpeg" "CONCRETOS ECOLOGICOS/IAP-063/_proceso.jpeg"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-063/TERMINADO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/IAP-063/TERMINADO.jpeg" "CONCRETOS ECOLOGICOS/IAP-063/_terminado.jpeg"; fi
if [ -d "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-064-2026" ]; then mv "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-064-2026" "CONCRETOS ECOLOGICOS/TERRA-064"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-064/INICIO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-064/INICIO.jpeg" "CONCRETOS ECOLOGICOS/TERRA-064/_inicio.jpeg"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-064/PROCESO.JPG" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-064/PROCESO.JPG" "CONCRETOS ECOLOGICOS/TERRA-064/_proceso.jpg"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-064/TERMINADO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-064/TERMINADO.jpeg" "CONCRETOS ECOLOGICOS/TERRA-064/_terminado.jpeg"; fi
if [ -d "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-065-2026" ]; then mv "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-065-2026" "CONCRETOS ECOLOGICOS/TERRA-065"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-065/INICIO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-065/INICIO.jpeg" "CONCRETOS ECOLOGICOS/TERRA-065/_inicio.jpeg"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-065/PROCESO.JPG" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-065/PROCESO.JPG" "CONCRETOS ECOLOGICOS/TERRA-065/_proceso.jpg"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-065/TERMINADO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-065/TERMINADO.jpeg" "CONCRETOS ECOLOGICOS/TERRA-065/_terminado.jpeg"; fi
if [ -d "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-066-2026" ]; then mv "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-066-2026" "CONCRETOS ECOLOGICOS/IAP-066"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-066/INICIO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/IAP-066/INICIO.jpeg" "CONCRETOS ECOLOGICOS/IAP-066/_inicio.jpeg"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-066/PROCESO.JPG" ]; then mv "CONCRETOS ECOLOGICOS/IAP-066/PROCESO.JPG" "CONCRETOS ECOLOGICOS/IAP-066/_proceso.jpg"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-066/TERMINADO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/IAP-066/TERMINADO.jpeg" "CONCRETOS ECOLOGICOS/IAP-066/_terminado.jpeg"; fi
if [ -d "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-067-2026" ]; then mv "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-067-2026" "CONCRETOS ECOLOGICOS/IAP-067"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-067/INICIO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/IAP-067/INICIO.jpeg" "CONCRETOS ECOLOGICOS/IAP-067/_inicio.jpeg"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-067/PROCESO.JPG" ]; then mv "CONCRETOS ECOLOGICOS/IAP-067/PROCESO.JPG" "CONCRETOS ECOLOGICOS/IAP-067/_proceso.jpg"; fi
if [ -d "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-086-2026" ]; then mv "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-086-2026" "CONCRETOS ECOLOGICOS/TERRA-086"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-086/INICIO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-086/INICIO.jpeg" "CONCRETOS ECOLOGICOS/TERRA-086/_inicio.jpeg"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-086/PROCESO.JPG" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-086/PROCESO.JPG" "CONCRETOS ECOLOGICOS/TERRA-086/_proceso.jpg"; fi
if [ -f "CONCRETOS ECOLOGICOS/TERRA-086/TERMINADO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/TERRA-086/TERMINADO.jpeg" "CONCRETOS ECOLOGICOS/TERRA-086/_terminado.jpeg"; fi
if [ -d "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-087-2026" ]; then mv "CONCRETOS ECOLOGICOS/MT-DGOP-FAISMUN-LPN-087-2026" "CONCRETOS ECOLOGICOS/IAP-087"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-087/INICIO.jpeg" ]; then mv "CONCRETOS ECOLOGICOS/IAP-087/INICIO.jpeg" "CONCRETOS ECOLOGICOS/IAP-087/_inicio.jpeg"; fi
if [ -f "CONCRETOS ECOLOGICOS/IAP-087/PROCESO.JPG" ]; then mv "CONCRETOS ECOLOGICOS/IAP-087/PROCESO.JPG" "CONCRETOS ECOLOGICOS/IAP-087/_proceso.jpg"; fi
if [ -d "CONCRETOS HIDRAULICOS/MT-DGOP-FAISMUN-LPN-059-2026" ]; then mv "CONCRETOS HIDRAULICOS/MT-DGOP-FAISMUN-LPN-059-2026" "CONCRETOS HIDRAULICOS/AZTLAN-059"; fi
if [ -f "CONCRETOS HIDRAULICOS/AZTLAN-059/INICIO.jpeg" ]; then mv "CONCRETOS HIDRAULICOS/AZTLAN-059/INICIO.jpeg" "CONCRETOS HIDRAULICOS/AZTLAN-059/_inicio.jpeg"; fi
if [ -f "CONCRETOS HIDRAULICOS/AZTLAN-059/PROCESO-2.jpeg" ]; then mv "CONCRETOS HIDRAULICOS/AZTLAN-059/PROCESO-2.jpeg" "CONCRETOS HIDRAULICOS/AZTLAN-059/_proceso.jpeg"; fi
if [ -f "CONCRETOS HIDRAULICOS/AZTLAN-059/PROCESO.jpeg" ]; then mv "CONCRETOS HIDRAULICOS/AZTLAN-059/PROCESO.jpeg" "CONCRETOS HIDRAULICOS/AZTLAN-059/_proceso_2.jpeg"; fi
if [ -d "CONCRETOS HIDRAULICOS/MT-DGOP-IPDM-LPN-053-2026" ]; then mv "CONCRETOS HIDRAULICOS/MT-DGOP-IPDM-LPN-053-2026" "CONCRETOS HIDRAULICOS/FENA-053"; fi
if [ -f "CONCRETOS HIDRAULICOS/FENA-053/INICIO.jpeg" ]; then mv "CONCRETOS HIDRAULICOS/FENA-053/INICIO.jpeg" "CONCRETOS HIDRAULICOS/FENA-053/_inicio.jpeg"; fi
if [ -f "CONCRETOS HIDRAULICOS/FENA-053/PROCESO.jpeg" ]; then mv "CONCRETOS HIDRAULICOS/FENA-053/PROCESO.jpeg" "CONCRETOS HIDRAULICOS/FENA-053/_proceso.jpeg"; fi
if [ -f "CONCRETOS HIDRAULICOS/FENA-053/TERMINO.jpeg" ]; then mv "CONCRETOS HIDRAULICOS/FENA-053/TERMINO.jpeg" "CONCRETOS HIDRAULICOS/FENA-053/_terminado.jpeg"; fi
if [ -d "CONSTRUCCIÓN DE CARPETA ASFALTICA/MT-DGOP-FAISMUN-LPN-060-2026" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/MT-DGOP-FAISMUN-LPN-060-2026" "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060"; fi
if [ -f "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060/INICIAL.jpeg" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060/INICIAL.jpeg" "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060/_inicio.jpeg"; fi
if [ -f "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060/PROCESO.jpeg" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060/PROCESO.jpeg" "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060/_proceso.jpeg"; fi
if [ -f "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060/TERMINADO.jpeg" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060/TERMINADO.jpeg" "CONSTRUCCIÓN DE CARPETA ASFALTICA/MAMUTEE-060/_terminado.jpeg"; fi
if [ -d "CONSTRUCCIÓN DE CARPETA ASFALTICA/MT-DGOP-FAISMUN-LPN-092-2026" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/MT-DGOP-FAISMUN-LPN-092-2026" "CONSTRUCCIÓN DE CARPETA ASFALTICA/CARASTOL-092"; fi
if [ -f "CONSTRUCCIÓN DE CARPETA ASFALTICA/CARASTOL-092/INICIAL.jpeg" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/CARASTOL-092/INICIAL.jpeg" "CONSTRUCCIÓN DE CARPETA ASFALTICA/CARASTOL-092/_inicio.jpeg"; fi
if [ -f "CONSTRUCCIÓN DE CARPETA ASFALTICA/CARASTOL-092/PROCESO.jpeg" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/CARASTOL-092/PROCESO.jpeg" "CONSTRUCCIÓN DE CARPETA ASFALTICA/CARASTOL-092/_proceso.jpeg"; fi
if [ -d "CONSTRUCCIÓN DE CARPETA ASFALTICA/MT-DGOP-FAISMUN-LPN-095-2026" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/MT-DGOP-FAISMUN-LPN-095-2026" "CONSTRUCCIÓN DE CARPETA ASFALTICA/EDIT-095"; fi
if [ -f "CONSTRUCCIÓN DE CARPETA ASFALTICA/EDIT-095/INICIAL.jpeg" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/EDIT-095/INICIAL.jpeg" "CONSTRUCCIÓN DE CARPETA ASFALTICA/EDIT-095/_inicio.jpeg"; fi
if [ -f "CONSTRUCCIÓN DE CARPETA ASFALTICA/EDIT-095/PROCESO.jpeg" ]; then mv "CONSTRUCCIÓN DE CARPETA ASFALTICA/EDIT-095/PROCESO.jpeg" "CONSTRUCCIÓN DE CARPETA ASFALTICA/EDIT-095/_proceso.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT -DGOP-FAISMUN-LPN-084-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT -DGOP-FAISMUN-LPN-084-2026" "REHABILITACIÓN DE CARPETAS/JDJ-084"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/JDJ-084/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/JDJ-084/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/JDJ-084/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/JDJ-084/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/JDJ-084/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/JDJ-084/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/JDJ-084/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/JDJ-084/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/JDJ-084/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-050-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-050-2026" "REHABILITACIÓN DE CARPETAS/VERDE-050"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/VERDE-050/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/VERDE-050/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/VERDE-050/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/VERDE-050/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/VERDE-050/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/VERDE-050/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/VERDE-050/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/VERDE-050/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/VERDE-050/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-051-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-051-2026" "REHABILITACIÓN DE CARPETAS/SINFRA-051"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/SINFRA-051/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/SINFRA-051/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/SINFRA-051/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/SINFRA-051/PROCESO-2.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/SINFRA-051/PROCESO-2.jpeg" "REHABILITACIÓN DE CARPETAS/SINFRA-051/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/SINFRA-051/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/SINFRA-051/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/SINFRA-051/_proceso_2.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/SINFRA-051/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/SINFRA-051/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/SINFRA-051/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-052-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-052-2026" "REHABILITACIÓN DE CARPETAS/EDIT-052"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/EDIT-052/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/EDIT-052/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/EDIT-052/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/EDIT-052/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/EDIT-052/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/EDIT-052/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/EDIT-052/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/EDIT-052/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/EDIT-052/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-058-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-058-2026" "REHABILITACIÓN DE CARPETAS/ARPLEX-058"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/ARPLEX-058/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/ARPLEX-058/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/ARPLEX-058/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/ARPLEX-058/PROCESO-2.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/ARPLEX-058/PROCESO-2.jpeg" "REHABILITACIÓN DE CARPETAS/ARPLEX-058/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/ARPLEX-058/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/ARPLEX-058/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/ARPLEX-058/_proceso_2.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-078-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-078-2026" "REHABILITACIÓN DE CARPETAS/CARASTOL-078"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/CARASTOL-078/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/CARASTOL-078/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/CARASTOL-078/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/CARASTOL-078/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/CARASTOL-078/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/CARASTOL-078/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/CARASTOL-078/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/CARASTOL-078/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/CARASTOL-078/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-081-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-081-2026" "REHABILITACIÓN DE CARPETAS/CREA-081"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/CREA-081/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/CREA-081/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/CREA-081/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/CREA-081/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/CREA-081/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/CREA-081/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-082-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-082-2026" "REHABILITACIÓN DE CARPETAS/REDNI-082"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/REDNI-082/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/REDNI-082/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/REDNI-082/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/REDNI-082/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/REDNI-082/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/REDNI-082/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/REDNI-082/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/REDNI-082/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/REDNI-082/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-083-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-083-2026" "REHABILITACIÓN DE CARPETAS/ESCARPIO-083"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/ESCARPIO-083/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/ESCARPIO-083/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/ESCARPIO-083/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/ESCARPIO-083/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/ESCARPIO-083/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/ESCARPIO-083/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/ESCARPIO-083/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/ESCARPIO-083/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/ESCARPIO-083/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-089-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-089-2026" "REHABILITACIÓN DE CARPETAS/MAMUTEE-089"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/MAMUTEE-089/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/MAMUTEE-089/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/MAMUTEE-089/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/MAMUTEE-089/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/MAMUTEE-089/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/MAMUTEE-089/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/MAMUTEE-089/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/MAMUTEE-089/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/MAMUTEE-089/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-090-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-090-2026" "REHABILITACIÓN DE CARPETAS/SINFRA-090"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/SINFRA-090/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/SINFRA-090/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/SINFRA-090/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/SINFRA-090/PROCESO-2.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/SINFRA-090/PROCESO-2.jpeg" "REHABILITACIÓN DE CARPETAS/SINFRA-090/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/SINFRA-090/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/SINFRA-090/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/SINFRA-090/_proceso_2.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-091-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-FAISMUN-LPN-091-2026" "REHABILITACIÓN DE CARPETAS/ESCARPIO-091"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/ESCARPIO-091/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/ESCARPIO-091/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/ESCARPIO-091/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/ESCARPIO-091/PROCESO-2.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/ESCARPIO-091/PROCESO-2.jpeg" "REHABILITACIÓN DE CARPETAS/ESCARPIO-091/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/ESCARPIO-091/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/ESCARPIO-091/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/ESCARPIO-091/_proceso_2.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-IPDM-LPN-054-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-IPDM-LPN-054-2026" "REHABILITACIÓN DE CARPETAS/FENA-054"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/FENA-054/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/FENA-054/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/FENA-054/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/FENA-054/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/FENA-054/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/FENA-054/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/FENA-054/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/FENA-054/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/FENA-054/_terminado.jpeg"; fi
if [ -d "REHABILITACIÓN DE CARPETAS/MT-DGOP-IPDM-LPN-056-2026" ]; then mv "REHABILITACIÓN DE CARPETAS/MT-DGOP-IPDM-LPN-056-2026" "REHABILITACIÓN DE CARPETAS/RASECA-056"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/RASECA-056/INICIAL.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/RASECA-056/INICIAL.jpeg" "REHABILITACIÓN DE CARPETAS/RASECA-056/_inicio.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/RASECA-056/PROCESO-2.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/RASECA-056/PROCESO-2.jpeg" "REHABILITACIÓN DE CARPETAS/RASECA-056/_proceso.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/RASECA-056/PROCESO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/RASECA-056/PROCESO.jpeg" "REHABILITACIÓN DE CARPETAS/RASECA-056/_proceso_2.jpeg"; fi
if [ -f "REHABILITACIÓN DE CARPETAS/RASECA-056/TERMINADO.jpeg" ]; then mv "REHABILITACIÓN DE CARPETAS/RASECA-056/TERMINADO.jpeg" "REHABILITACIÓN DE CARPETAS/RASECA-056/_terminado.jpeg"; fi
if [ -d "SENDEROS Y PARQUES/MT-DGOP-AVGFDyFCI-LPN-077-2026" ]; then mv "SENDEROS Y PARQUES/MT-DGOP-AVGFDyFCI-LPN-077-2026" "SENDEROS Y PARQUES/ICI-077"; fi
if [ -f "SENDEROS Y PARQUES/ICI-077/INICIAL.jpeg" ]; then mv "SENDEROS Y PARQUES/ICI-077/INICIAL.jpeg" "SENDEROS Y PARQUES/ICI-077/_inicio.jpeg"; fi
if [ -f "SENDEROS Y PARQUES/ICI-077/PROCESO-2.jpeg" ]; then mv "SENDEROS Y PARQUES/ICI-077/PROCESO-2.jpeg" "SENDEROS Y PARQUES/ICI-077/_proceso.jpeg"; fi
if [ -f "SENDEROS Y PARQUES/ICI-077/PROCESO.jpeg" ]; then mv "SENDEROS Y PARQUES/ICI-077/PROCESO.jpeg" "SENDEROS Y PARQUES/ICI-077/_proceso_2.jpeg"; fi
if [ -d "SENDEROS Y PARQUES/MT-DGOP-FAISMUN-LPN-076-2026" ]; then mv "SENDEROS Y PARQUES/MT-DGOP-FAISMUN-LPN-076-2026" "SENDEROS Y PARQUES/ICI-076"; fi
if [ -f "SENDEROS Y PARQUES/ICI-076/INICIAL.jpeg" ]; then mv "SENDEROS Y PARQUES/ICI-076/INICIAL.jpeg" "SENDEROS Y PARQUES/ICI-076/_inicio.jpeg"; fi
if [ -f "SENDEROS Y PARQUES/ICI-076/PROCESO.jpeg" ]; then mv "SENDEROS Y PARQUES/ICI-076/PROCESO.jpeg" "SENDEROS Y PARQUES/ICI-076/_proceso.jpeg"; fi
if [ -d "SENDEROS Y PARQUES/MT-DGOP-FAISMUN-LPN-094-2026" ]; then mv "SENDEROS Y PARQUES/MT-DGOP-FAISMUN-LPN-094-2026" "SENDEROS Y PARQUES/EAPRO-094"; fi
if [ -f "SENDEROS Y PARQUES/EAPRO-094/INICIAL.jpeg" ]; then mv "SENDEROS Y PARQUES/EAPRO-094/INICIAL.jpeg" "SENDEROS Y PARQUES/EAPRO-094/_inicio.jpeg"; fi
if [ -f "SENDEROS Y PARQUES/EAPRO-094/PROCESO.jpeg" ]; then mv "SENDEROS Y PARQUES/EAPRO-094/PROCESO.jpeg" "SENDEROS Y PARQUES/EAPRO-094/_proceso.jpeg"; fi
if [ -d "SENDEROS Y PARQUES/MT-DGOP-IPDM-LPN-057-2026" ]; then mv "SENDEROS Y PARQUES/MT-DGOP-IPDM-LPN-057-2026" "SENDEROS Y PARQUES/TERRA-057"; fi
if [ -f "SENDEROS Y PARQUES/TERRA-057/INICIO.jpeg" ]; then mv "SENDEROS Y PARQUES/TERRA-057/INICIO.jpeg" "SENDEROS Y PARQUES/TERRA-057/_inicio.jpeg"; fi
if [ -f "SENDEROS Y PARQUES/TERRA-057/PROCESO.jpeg" ]; then mv "SENDEROS Y PARQUES/TERRA-057/PROCESO.jpeg" "SENDEROS Y PARQUES/TERRA-057/_proceso.jpeg"; fi
if [ -f "SENDEROS Y PARQUES/TERRA-057/TERMINADO.jpeg" ]; then mv "SENDEROS Y PARQUES/TERRA-057/TERMINADO.jpeg" "SENDEROS Y PARQUES/TERRA-057/_terminado.jpeg"; fi
if [ -d "SEÑALAMIENTO/SEÑALAMIENTO HORIZONTAL Y VERTICAL EN DIVERSAS CALLES" ]; then mv "SEÑALAMIENTO/SEÑALAMIENTO HORIZONTAL Y VERTICAL EN DIVERSAS CALLES" "SEÑALAMIENTO/VIFUD-049"; fi
if [ -f "SEÑALAMIENTO/VIFUD-049/FINAL.jpeg" ]; then mv "SEÑALAMIENTO/VIFUD-049/FINAL.jpeg" "SEÑALAMIENTO/VIFUD-049/_terminado.jpeg"; fi
if [ -f "SEÑALAMIENTO/VIFUD-049/INICIAL.jpeg" ]; then mv "SEÑALAMIENTO/VIFUD-049/INICIAL.jpeg" "SEÑALAMIENTO/VIFUD-049/_inicio.jpeg"; fi
if [ -f "SEÑALAMIENTO/VIFUD-049/PROCESO (2).jpeg" ]; then mv "SEÑALAMIENTO/VIFUD-049/PROCESO (2).jpeg" "SEÑALAMIENTO/VIFUD-049/_proceso.jpeg"; fi
if [ -d "SLURRY/MT-DGOP-FAISMUN-LPN-079-2026" ]; then mv "SLURRY/MT-DGOP-FAISMUN-LPN-079-2026" "SLURRY/SAQEB-079"; fi
if [ -f "SLURRY/SAQEB-079/INICIAL.jpeg" ]; then mv "SLURRY/SAQEB-079/INICIAL.jpeg" "SLURRY/SAQEB-079/_inicio.jpeg"; fi
if [ -f "SLURRY/SAQEB-079/PROCESO.jpeg" ]; then mv "SLURRY/SAQEB-079/PROCESO.jpeg" "SLURRY/SAQEB-079/_proceso.jpeg"; fi
if [ -f "SLURRY/SAQEB-079/TERMINADO.jpeg" ]; then mv "SLURRY/SAQEB-079/TERMINADO.jpeg" "SLURRY/SAQEB-079/_terminado.jpeg"; fi
if [ -d "SLURRY/MT-DGOP-FAISMUN-LPN-080-2026" ]; then mv "SLURRY/MT-DGOP-FAISMUN-LPN-080-2026" "SLURRY/GZALES-080"; fi
if [ -f "SLURRY/GZALES-080/INICIAL.jpeg" ]; then mv "SLURRY/GZALES-080/INICIAL.jpeg" "SLURRY/GZALES-080/_inicio.jpeg"; fi
if [ -f "SLURRY/GZALES-080/PROCESO.jpeg" ]; then mv "SLURRY/GZALES-080/PROCESO.jpeg" "SLURRY/GZALES-080/_proceso.jpeg"; fi
if [ -f "SLURRY/GZALES-080/TERMINADO.jpeg" ]; then mv "SLURRY/GZALES-080/TERMINADO.jpeg" "SLURRY/GZALES-080/_terminado.jpeg"; fi
if [ -d "SLURRY/MT-DGOP-FAISMUN-LPN-085-2026" ]; then mv "SLURRY/MT-DGOP-FAISMUN-LPN-085-2026" "SLURRY/TOVAR-085"; fi
if [ -f "SLURRY/TOVAR-085/FINAL.jpeg" ]; then mv "SLURRY/TOVAR-085/FINAL.jpeg" "SLURRY/TOVAR-085/_terminado.jpeg"; fi
if [ -f "SLURRY/TOVAR-085/INICIAL.jpeg" ]; then mv "SLURRY/TOVAR-085/INICIAL.jpeg" "SLURRY/TOVAR-085/_inicio.jpeg"; fi
if [ -f "SLURRY/TOVAR-085/PROCESO.jpeg" ]; then mv "SLURRY/TOVAR-085/PROCESO.jpeg" "SLURRY/TOVAR-085/_proceso.jpeg"; fi
if [ -d "SLURRY/MT-DGOP-IPDM-LPN-055-2026" ]; then mv "SLURRY/MT-DGOP-IPDM-LPN-055-2026" "SLURRY/EAPRO-055"; fi
if [ -f "SLURRY/EAPRO-055/INICIO.jpeg" ]; then mv "SLURRY/EAPRO-055/INICIO.jpeg" "SLURRY/EAPRO-055/_inicio.jpeg"; fi
if [ -f "SLURRY/EAPRO-055/PROCESO.jpeg" ]; then mv "SLURRY/EAPRO-055/PROCESO.jpeg" "SLURRY/EAPRO-055/_proceso.jpeg"; fi
if [ -f "SLURRY/EAPRO-055/TERMINADO.jpeg" ]; then mv "SLURRY/EAPRO-055/TERMINADO.jpeg" "SLURRY/EAPRO-055/_terminado.jpeg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-068-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-068-2026" "TECHADO/CREA-068"; fi
if [ -f "TECHADO/CREA-068/INICIAL.jpeg" ]; then mv "TECHADO/CREA-068/INICIAL.jpeg" "TECHADO/CREA-068/_inicio.jpeg"; fi
if [ -f "TECHADO/CREA-068/PROCESO.jpeg" ]; then mv "TECHADO/CREA-068/PROCESO.jpeg" "TECHADO/CREA-068/_proceso.jpeg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-069-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-069-2026" "TECHADO/CREA-069"; fi
if [ -f "TECHADO/CREA-069/INICIAL.jpeg" ]; then mv "TECHADO/CREA-069/INICIAL.jpeg" "TECHADO/CREA-069/_inicio.jpeg"; fi
if [ -f "TECHADO/CREA-069/PROCESO.jpeg" ]; then mv "TECHADO/CREA-069/PROCESO.jpeg" "TECHADO/CREA-069/_proceso.jpeg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-070-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-070-2026" "TECHADO/SBSL-070"; fi
if [ -f "TECHADO/SBSL-070/INICIAL.jpeg" ]; then mv "TECHADO/SBSL-070/INICIAL.jpeg" "TECHADO/SBSL-070/_inicio.jpeg"; fi
if [ -f "TECHADO/SBSL-070/PROCESO.jpeg" ]; then mv "TECHADO/SBSL-070/PROCESO.jpeg" "TECHADO/SBSL-070/_proceso.jpeg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-071-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-071-2026" "TECHADO/SBSL-071"; fi
if [ -f "TECHADO/SBSL-071/INICIO.jpeg" ]; then mv "TECHADO/SBSL-071/INICIO.jpeg" "TECHADO/SBSL-071/_inicio.jpeg"; fi
if [ -f "TECHADO/SBSL-071/PROCESO.jpeg" ]; then mv "TECHADO/SBSL-071/PROCESO.jpeg" "TECHADO/SBSL-071/_proceso.jpeg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-072-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-072-2026" "TECHADO/FENA-072"; fi
if [ -f "TECHADO/FENA-072/INICIAL.jpeg" ]; then mv "TECHADO/FENA-072/INICIAL.jpeg" "TECHADO/FENA-072/_inicio.jpeg"; fi
if [ -f "TECHADO/FENA-072/PROCESO.jpeg" ]; then mv "TECHADO/FENA-072/PROCESO.jpeg" "TECHADO/FENA-072/_proceso.jpeg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-073-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-073-2026" "TECHADO/FENA-073"; fi
if [ -f "TECHADO/FENA-073/INICIAL.jpeg" ]; then mv "TECHADO/FENA-073/INICIAL.jpeg" "TECHADO/FENA-073/_inicio.jpeg"; fi
if [ -f "TECHADO/FENA-073/PROCESO.jpeg" ]; then mv "TECHADO/FENA-073/PROCESO.jpeg" "TECHADO/FENA-073/_proceso.jpeg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-074-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-074-2026" "TECHADO/REDNI-074"; fi
if [ -f "TECHADO/REDNI-074/INICIAL.jpeg" ]; then mv "TECHADO/REDNI-074/INICIAL.jpeg" "TECHADO/REDNI-074/_inicio.jpeg"; fi
if [ -f "TECHADO/REDNI-074/PROCESO.jpeg" ]; then mv "TECHADO/REDNI-074/PROCESO.jpeg" "TECHADO/REDNI-074/_proceso.jpeg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-075-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-075-2026" "TECHADO/INOVA-075"; fi
if [ -f "TECHADO/INOVA-075/INICIAL.jpg" ]; then mv "TECHADO/INOVA-075/INICIAL.jpg" "TECHADO/INOVA-075/_inicio.jpg"; fi
if [ -f "TECHADO/INOVA-075/PROCESO.jpg" ]; then mv "TECHADO/INOVA-075/PROCESO.jpg" "TECHADO/INOVA-075/_proceso.jpg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-088-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-088-2026" "TECHADO/MAMUTEE-088"; fi
if [ -f "TECHADO/MAMUTEE-088/INICIAL.jpeg" ]; then mv "TECHADO/MAMUTEE-088/INICIAL.jpeg" "TECHADO/MAMUTEE-088/_inicio.jpeg"; fi
if [ -f "TECHADO/MAMUTEE-088/PROCESO.jpeg" ]; then mv "TECHADO/MAMUTEE-088/PROCESO.jpeg" "TECHADO/MAMUTEE-088/_proceso.jpeg"; fi
if [ -d "TECHADO/MT-DGOP-FAISMUN-LPN-093-2026" ]; then mv "TECHADO/MT-DGOP-FAISMUN-LPN-093-2026" "TECHADO/FENA-093"; fi
if [ -f "TECHADO/FENA-093/INICIAL.jpeg" ]; then mv "TECHADO/FENA-093/INICIAL.jpeg" "TECHADO/FENA-093/_inicio.jpeg"; fi
if [ -f "TECHADO/FENA-093/PROCESO.jpeg" ]; then mv "TECHADO/FENA-093/PROCESO.jpeg" "TECHADO/FENA-093/_proceso.jpeg"; fi
